name: Android AAB Build

on:
  pull_request:
    branches:
      - main

jobs:
  aab-build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > $GITHUB_WORKSPACE/keystore.jks

      - name: Build Release AAB
        run: ./gradlew bundleRelease
        env:
          KEYSTORE_FILE_PATH: ${{ github.workspace }}/keystore.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Extract AAB name
        run: |
          AAB_FILE_PATH=$(ls app/build/outputs/bundle/release/*.aab | head -n 1)
          AAB_GRADLE_NAME=$(basename "AAB_FILE_PATH" .aab)
          echo "AAB_NAME=$AAB_GRADLE_NAME" >> $GITHUB_ENV

      - name: Upload AAB as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.AAB_NAME }}
          path: app/build/outputs/bundle/release/*.aab
          retention-days: 30

      - name: Clean up keystore
        if: always()
        run: rm -f $GITHUB_WORKSPACE/keystore.jks